--- name: RADIUS_NPS
  hosts: AOS
  remote_user: admin
  
  -name: Configure RADIUS aaa
    ios_command:
      commands: radius-server host 10.100.128.117 auth-port 1812 acct-port 1813 key secretSWaos!
      commands: aaa authentication login privilege-mode
      
  -name: Configure RADIUS sso
    ios_command:
      commands: aaa authentication console login radius local
      commands: aaa authentication console enable radius local
      commands: aaa authentication telnet login radius local
      commands: aaa authentication telnet enable radius local
      commands: aaa authentication web login radius local
      commands: aaa authentication web enable radius local
      commands: aaa authentication ssh login radius local
      commands: aaa authentication ssh enable radius local
  
  -name: Configure RADIUS accounting
    ios_command:
      commands: aaa accounting network start-stop radius
      commands: aaa accounting exec start-stop radius
      commands: aaa accounting system start-stop radius
      
